R_MOTOR_B_PIN = 17
R_MOTOR_F_PIN = 27
L_MOTOR_B_PIN = 23
L_MOTOR_F_PIN = 24

R_SENSOR_ECHO_PIN = 5
R_SENSOR_TRIGGER_PIN = 6
L_SENSOR_ECHO_PIN = 13
L_SENSOR_TRIGGER_PIN = 26

R_LED_PIN = 14
L_LED_PIN = 20

R_ENCODER_PIN = 8
L_ENCODER_PIN = 7

BUZZER_PIN = 21
